version: "3.7"

services:
  app:
    image: invoiceninja/invoiceninja:5
    restart: always
    cap_add:
      - SYS_ADMIN
    env_file: ../../secrets/invoiceninja/ninja.env
    environment:
      - APP_DEBUG=true
      - APP_URL=https://localhost
      - APP_CIPHER='AES-256-CBC'
      - MULTI_DB_ENABLED=false
      - DB_HOST1=db
      - DB_USERNAME1=ninja
      - DB_DATABASE1=ninja
      - PHANTOMJS_PDF_GENERATION=false
      - SNAPPDF_EXECUTABLE_PATH="/usr/bin/chromium-browser"
      - SNAPPDF_SKIP_DOWNLOAD=true
    volumes:
      - ../caddy/www/invoiceninja/public:/var/www/app/public:rw,delegated
      - ../caddy/www/invoiceninja/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks:
      - proxied

  db:
    image: mysql:5
    restart: always
    env_file: ../../secrets/invoiceninja/db.env
    environment:
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - MYSQL_DATABASE=ninja
    volumes:
      # - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - proxied

  # THIS IS ONLY A VALID CONFIGURATION FOR IN 4. DO NOT USE FOR IN 5.
  # cron:
  #   image: invoiceninja/invoiceninja:alpine-4
  #   volumes:
  #     -  storage:/var/www/app/storage
  #     -  logo:/var/www/app/public/logo
  #     -  public:/var/www/app/public
  #   entrypoint: |
  #     /bin/sh -c 'sh -s <<EOF
  #     trap "break;exit" SIGHUP SIGINT SIGTERM
  #     sleep 300s
  #     while /bin/true; do
  #       ./artisan ninja:send-invoices
  #       ./artisan ninja:send-reminders
  #       sleep 1d
  #     done
  #     EOF'
  #   networks:
  #     - invoiceninja

networks:
  invoiceninja:

networks:
  proxied:
    external:
      name: proxied

