version: "3.7"
services:
  nginx:
    depends_on:
      - astrid_tech_api
    image: staticfloat/nginx-certbot:latest
    volumes:
      - ./deployment/nginx:/etc/nginx/user.conf.d:ro
      - astrid_tech_static:/www/static/
      - letsencrypt:/etc/letsencrypt
    environment:
      CERTBOT_EMAIL: astridyu3.14@gmail.com
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    restart: unless-stopped
    networks:
      - proxied

volumes:
  letsencrypt:

networks:
  proxied:
    external:
      name: proxied
