version: "3.7"

services:
  server:
    image: customized-caddy
    build:
      args:
        - plugins="jwt,login"
      target: github.com/abiosoft/caddy-docker.git
    restart: always
    volumes:
      - ./config/:/etc/caddy/
      - ./www:/var/www
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxied

networks:
  proxied:
    external:
      name: proxied
