version: "3.7"
services:
  dokuwiki:
    image: ghcr.io/linuxserver/dokuwiki
    hostname: dnddokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data:/config
    expose:
      - "80"
    ports:
      - 8000:80
    restart: unless-stopped
    networks:
      - proxied

networks:
  proxied:
    external:
      name: proxied
