version: "3.3"

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    hostname: firefly
    restart: unless-stopped
    volumes:
      - ../caddy/www/firefly/upload:/var/www/html/storage/upload
    env_file: ../../secrets/firefly/firefly.env
    expose:
      - "8080"
    depends_on:
      - fireflyiiidb
    networks:
      - vpn
      - net
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest
    env_file: ../../secrets/firefly/fireflydb.env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_DATABASE=firefly
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - net

networks:
  net:
  proxied:
    external:
      name: proxied
  vpn:
    external:
      name: vpn
