version: "3.7"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    hostname: dndbookstack
    env_file: ../../secrets/dndbookstack/wiki.env
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://dndwiki.astrid.tech
      - DB_HOST=bookstack_db
      - DB_DATABASE=bookstackapp
      - DB_USER=bookstack
    volumes:
      - ./data/config:/config
    expose:
      - "80"
      - "443"
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
      - proxied
      - net

  bookstack_db:
    image: yobasystems/alpine-mariadb:latest
    env_file: ../../secrets/dndbookstack/db.env
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - net

networks:
  net:
  proxied:
    external:
      name: proxied
